server:
  port: 8081

spring:
  application:
    name: restaurant-service

  # Database configuration (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5433/restaurant_service?stringtype=unspecified
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456

    # JPA configuration
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect


  # Kafka configuration
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: restaurant-service-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    com.example.restaurant: INFO
    org.springframework.web: INFO
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR


eureka:
  client:
    serviceUrl:
      # Định nghĩa URL của Eureka Server
      defaultZone: http://discovery-server:8671/eureka/
    region: default
  instance:
    # Tên host cho việc đăng ký
    hostname: localhost
    # Không ưu tiên địa chỉ IP hơn hostname
    prefer-ip-address: false
    # Định dạng ID instance khi đăng ký với Eureka (ví dụ: order-service:8181)
    instance-id: ${spring.application.name}:${server.port}
