server:
  port: 8082

spring:
  application:
    name: payment-service

  # --- CẤU HÌNH REDIS (MỚI THÊM) ---
  data:
    redis:
      # Nếu không có biến môi trường SPRING_REDIS_HOST, mặc định dùng localhost (cho debug local)
      # Khi chạy docker-compose, ta sẽ set SPRING_REDIS_HOST=redis
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}

  # Database configuration (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5434/payment_service?stringtype=unspecified
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456

  # JPA configuration
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          default_schema: payment
          hbm2ddl:
            create_schemas: true


  # Kafka configuration
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
#
#    consumer:
#      group-id: payment-service-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "com.example.common_messaging.dto.event"
#        # BẮT BUỘ phải khai báo chính xác class đầy đủ
#        spring.json.value.default.type: com.example.common_messaging.dto.event.OrderCreatedEvent
#        # Nếu có nhiều event thì dùng type mapping (cách này chắc ăn hơn)
#        spring.json.type.mapping: >
#          orderCreatedEvent:com.example.common_messaging.dto.event.OrderCreatedEvent,
#          orderRejectedEvent:com.example.common_messaging.dto.event.OrderRejectedEvent
#
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.json.add.type.headers: false   # Order Service cũng phải có dòng này (bạn đã có rồi)

logging:
  level:
    com.example.payment: INFO
    org.springframework.web: INFO
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR

# Cấu hình thanh toán VNPAY
vnp:
  pay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  tmnCode: GS884LF7
  hashSecret: 3OZWA90359NGJYQHBANJRV2AD5ZRUDW2
  returnUrl: http://localhost:8082/api/payments/callback
  refund:
    url: https://sandbox.vnpayment.vn/merchant_webapi/merchant.html
eureka:
  client:
    serviceUrl:
      # Định nghĩa URL của Eureka Server
      defaultZone: http://discovery-server:8671/eureka
    region: default
  instance:
    # Tên host cho việc đăng ký
    hostname: localhost
    # Không ưu tiên địa chỉ IP hơn hostname
    prefer-ip-address: false
    # Định dạng ID instance khi đăng ký với Eureka (ví dụ: order-service:8181)
    instance-id: ${spring.application.name}:${server.port}

-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl