version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  # Cấu hình Database
  order-db:
    image: postgres:14
    container_name: order-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: order_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

  restaurant-db:
    image: postgres:14
    container_name: restaurant-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: restaurant_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

  payment-db:
    image: postgres:14
    container_name: payment-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: payment_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

  order-service:
    build:
      context: .
      dockerfile: order-service/order-container/Dockerfile
    container_name: order-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - order-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/order_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  restaurant-service:
    build:
      context: .
      dockerfile: restaurant-service/restaurant-container/Dockerfile
    container_name: restaurant-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - restaurant-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://restaurant-db:5432/restaurant_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  payment-service:
    build:
      context: .
      dockerfile: paymentService/paymentContainer/Dockerfile
    container_name: payment-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - payment-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-db:5432/payment_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: payment
      SPRING_JPA_PROPERTIES_HIBERNATE_HBM2DDL_CREATE_SCHEMAS: true
