version: '3.9'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - microservices-network

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
    networks:
      - microservices-network

  # ==================== DISCOVERY SERVER (EUREKA) ====================
  discovery-server:
     build:
       context: .
       dockerfile: discovery-server/Dockerfile
     container_name: discovery-server
     ports:
       - "8671:8671"
     environment:
       - EUREKA_CLIENT_REGISTERWITH_EUREKA=false
       - EUREKA_CLIENT_FETCHREGISTRY=false
     healthcheck:
       test: [ "CMD", "curl", "-f", "http://localhost:8671/actuator/health" ]
       interval: 30s
       timeout: 10s
       retries: 5
     networks:
       - microservices-network

#   ==================== API GATEWAY ====================
  api-gateway:
     build:
       context: .
       dockerfile: api-gateway/Dockerfile
     container_name: api-gateway
     ports:
       - "8083:8083"
     depends_on:
       - discovery-server
     environment:
       - SPRING_CLOUD_COMPATIBILITY_VERIFIER_ENABLED=false
       - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8671/eureka/
       - SERVER_PORT=8083
     networks:
       - microservices-network

    # ==================== DATABASES ====================
  # 1. ORDER DB
  order-db:
    image: postgres:14
    container_name: order-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: order_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./order_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
      - ./postgres_data/order:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d order_service"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  # 2. RESTAURANT DB (Đã sửa lại cho đúng)
  restaurant-db:
    image: postgres:14
    container_name: restaurant-db
    ports:
      - "5433:5432" # Map ra ngoài cổng 5433
    environment:
      POSTGRES_DB: restaurant_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./restaurant_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
      - ./postgres_data/restaurant:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d restaurant_service"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  # 3. PAYMENT DB (Tách riêng ra)
  payment-db:
    image: postgres:14
    container_name: payment-db
    ports:
      - "5434:5432" # Map ra ngoài cổng 5434
    environment:
      POSTGRES_DB: payment_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./payment_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
      - ./postgres_data/payment:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payment_service"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  order-service:
    build:
      context: .
      dockerfile: order-service/order-container/Dockerfile
    container_name: order-service
    ports:
      - "8181:8181"
    depends_on:
      order-db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/order_service?stringtype=unspecified
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - microservices-network

  restaurant-service:
    build:
      context: .
      dockerfile: restaurant-service/restaurant-container/Dockerfile
    container_name: restaurant-service
    ports:
      - "8081:8081"
    depends_on:
      restaurant-db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://restaurant-db:5432/restaurant_service?stringtype=unspecified
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - microservices-network

  payment-service:
    build:
      context: .
      dockerfile: paymentService/paymentContainer/Dockerfile
    container_name: payment-service
    ports:
      - "8082:8082"
    depends_on:
      payment-db:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-db:5432/payment_service?stringtype=unspecified
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: payment
      SPRING_JPA_PROPERTIES_HIBERNATE_HBM2DDL_CREATE_SCHEMAS: true
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge



